name: Build

on:  
  push:
    branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Checkout archive repo
      uses: actions/checkout@v4
      with:
        repository: StephenNneji/demo_recv
        path: RAT
    - name: Build and Deploy Docs
      run: |
        cd RAT
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git config --unset-all http.https://github.com/.extraheader
        git add -A
        git commit -m "Publish Documentation" || true
        git push
