name: Build

on:  
  push:
    branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        ref: generated_source
        path: rat_source
    - name: Deploy Souce
      run: |
        wget https://github.com/RascalSoftware/RAT/releases/download/nightly/Linux.zip
        unzip Linux.zip
        rm -rf rat_source/*.c rat_source/*.cpp rat_source/*.h rat_source/*.hpp
        cd rat_source
        ls
