name: Build

on:  
  push:
    branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        ref: generated_source
        path: rat_source
    - name: Deploy Souce
      run: |
        wget https://www.dropbox.com/scl/fi/nx99ggfqmxxaz6m322b8t/Linux.zip?rlkey=c4hr315g2itu8n9wy1db7wb7r --output-document "Linux.zip"
        unzip Linux.zip
        rm -rf rat_source/*.c rat_source/*.cpp rat_source/*.h
        rsync -av compile/fullCompile/cppDeploy/ rat_source/
        cd rat_source
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -m "Deploy Source Code" || true
        git push
