name: Build

on:  
  push:
    branches: [ main ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      with:
        ref: generated_source
        path: rat_source
    - name: Deploy Souce
      run: |
        wget https://github.com/RascalSoftware/RAT/releases/download/nightly/Linux.zip
        unzip Linux.zip
        rm -rf rat_source/src
        mkdir rat_source/src
        rsync -av --exclude="*.mat" --exclude="interface/" --exclude="html/" --exclude="examples/" --exclude="*.dmr" --exclude=".gitignore" compile/fullCompile/codegen/lib/RATMain/ rat_source/src
        cd rat_source
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -m "Deploy Source Code" || true
        git push
